---
downloads: ~/.ansible-downloads/

pip_packages: []

brew_packages:
  - dockutil
  - tfenv
  - pyenv
  - zsh
  - ccat
  - cowsay
  - bash-completion
  - git
  - gh
  - go
  - gpg
  - fortune
  - helm
  - iperf
  - mdcat
  - nmap
  - openssl
  - telnet
  - readline
  - sqlite3
  - xz
  - zlib
  - wget
  - jq
  - curl
  - awscli
  - azure-cli
  - kubectl
  - kubeval
  - kustomize
  - docker
  - docker-compose
  - docker-machine
  - hadolint
  - hashicorp/tap/vault
  - hashicorp/tap/packer
  - ykman
  - pinentry-mac
  - yamllint

brew_taps:
  - homebrew/core
  - homebrew/cask
  - instrumenta/instrumenta

brew_cask_appdir: /Applications
brew_cask_packages:
  - postman
  - virtualbox
  - vagrant
  - slack
  - keybase
  - 1password
  - iterm2
  - intellij-idea-ce
  - pycharm-ce
  - google-chrome
  - zoomus
  - microsoft-teams
  - microsoft-office
  - azure-data-studio
  - microsoft-azure-storage-explorer
  - spotify

composer_packages: []
npm_packages: []
gem_packages: []

osx_script: "~/.osx --no-restart"

dockitems_remove:
  - Mail
  - Contacts
  - Reminders
  - Maps
  - Photos
  - Messages
  - FaceTime
  - iTunes
  - iBooks
  - App Store
  - Calendar
  - Music

dockitems_add:
  - name: Google Chrome
    path: "/Applications/Google Chrome.app"
  - name: Slack
    path: /Applications/Slack.app
  - name: iTerm
    path: /Applications/iTerm.app
  - name: Spotify
    path: /Applications/Spotify.app
  - name: IntelliJ IDEA CE
    path: "/Applications/IntelliJ IDEA CE.app"
  - name: PyCharm CE
    path: "/Applications/PyCharm CE.app"
  - name: Azure Data Studio
    path: "/Applications/Azure Data Studio.app"
  - name: Microsoft Azure Storage Explorer
    path: "/Applications/Microsoft Azure Storage Explorer.app"
  - name: OneDrive
    path: /Applications/OneDrive.app
  - name: Microsoft OneNote
    path: "/Applications/Microsoft OneNote.app"
