---
- hosts: local

  vars_files:
    - config.yml

  pre_tasks:
    - include_vars: "{{ item }}"
      with_fileglob:
        - "{{ playbook_dir }}/config.yml"
    - name: Ensure Homebrew is installed
      stat:
        path: /usr/local/bin/brew
      register: homebrew_check

  tasks:
    - include_tasks: tasks/homebrew.yml
    - include_tasks: tasks/ansible-setup.yml
    - include_tasks: tasks/packages.yml
    - include_tasks: tasks/scripts.yml
    - include_tasks: tasks/dock.yml
