---
# Update homebrew and upgrade all packages
- homebrew:
    update_homebrew: true
    upgrade_all: true

- name: Brew Taps.
  homebrew_tap:
    name: "{{ brew_taps }}"
    state: present

- name: Install Brew packages.
  homebrew:
    name: "{{ brew_packages }}"
    state: present

- name: Install Brew cask packages.
  homebrew_cask:
    name: "{{ brew_cask_packages }}"
    state: present
