---
# yamllint disable-line rule:truthy
on: push
name: yamllint
jobs:
  yamllint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Setup python
        uses: actions/setup-python@v1
        with:
          python-version: '3.x'
          architecture: x64
      - name: Update pip
        run: python -m pip install --upgrade pip
      - name: Install yamllint
        run: pip install yamllint
      - name: Run yamllint
        run: yamllint .
